### ISSUE TITLE
Execution error when using in angular-cli project

### ISSUE THREAD

**Issue by ManfredSteiner** [WoltersKluwerPL/ng-spin-kit#47]
Using a <sk-wave> component leads to following error:
```
Uncaught Error: Unexpected value 'WaveComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (http://localhost:3001/ng2/vendor.bundle.js:41390:34)
    at http://localhost:3001/ng2/vendor.bundle.js:54392:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3001/ng2/vendor.bundle.js:54374:54)
    at JitCompiler._loadModules (http://localhost:3001/ng2/vendor.bundle.js:65480:66)
    at JitCompiler._compileModuleAndComponents (http://localhost:3001/ng2/vendor.bundle.js:65439:52)
    at JitCompiler.compileModuleAsync (http://localhost:3001/ng2/vendor.bundle.js:65401:23)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3001/ng2/vendor.bundle.js:5394:25)
    at PlatformRef_.bootstrapModule (http://localhost:3001/ng2/vendor.bundle.js:5380:21)
    at Object.151 (http://localhost:3001/ng2/main.bundle.js:19:124)
```
Any ideas?

**Comment by ManfredSteiner** [comment]
When using Angular 2.4.x the kit works without problems. Using the latest version 4.2.4 the WaveComponent fails to start up.

See also [https://stackoverflow.com/questions/44755411](https://stackoverflow.com/questions/44755411)
